language: php

php:
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv
    version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f config/vhost-travis.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - ./vendor/bin/codecept run

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push https://$GITHUBKEY@github.com/dev-confidence/startup-startup $GIT_TAG

env:
  global:
    secure: RsWeLGe7Ghh+tPeuTO7c/O2SWJWLdpn2X+yE/UFttwNxOhmuRD7evpNBJpd7B0+tfd37Y9mlE3B7TPQvEQlUTDX1FVeFk0HXxYxNEdmPKTZvxQoM1E9yae0KX0/FqujPo0rpsN4PXfqDe/g3CRxa1cI24dBj/9wqpgdAWhYcWN8=
